### ISSUE TITLE
Can't extract RomFS

### ISSUE THREAD

**Issue by LarBob** [neobrain/braindump#17]
When I try to get the RomFS from the dump by running

```
ctrtool --romfs=romfs.bin --decompresscode 0004000000030700.cxi; ctrtool --romfsdir=romfs --intype=romfs romfs.bin
```

but when I do that, it just lists the help screen as if I had entered something wrong. I'm kind of a noob, so am I doing something really stupid/skipping a step? The other command for the ExeFS works fine. Thanks

**Comment by ghost** [comment]
Wtf ? It's not a single line.

**Comment by LarBob** [comment]
https://gyazo.com/f17ff8c36bb25e094bc5f0aebebcff88.png

**Comment by LarBob** [comment]
oh my god, I'm so dumb. I'm too used to Linux. You can separate commands like that and it works, haha. Sorry for wasting your time.

**Comment by ghost** [comment]
Does the directory "romfs" exist ?

**Comment by LarBob** [comment]
it's fine. I was making a stupid mistake. sorry
