### ISSUE TITLE
System Transfer doesn't dump properly.

### ISSUE THREAD

**Issue by ghost** [neobrain/braindump#2]
The ExeFS of System Transfer (0004001000021A00) does not dump properly. While dumping, it prints out an error when trying to access the banner. The resulting dump has a zeroed header, and trying to extract it with ctrtool results in an empty directory.

Error screenshot:
![scr_1_top_left](https://cloud.githubusercontent.com/assets/1269164/10747106/d3771466-7c0e-11e5-9d56-f9b0c992c19f.png)

**Comment by neobrain** [comment]
Reproduced with title 0x0004001000022A00. As far as I can tell, while running the system transfer utility, the home button cannot be used to switch to the Home Menu (can you confirm this?). Hence I suppose the application simply does not ship with a banner.

This should be verified by dumping the raw application using uncart, I suppose.

**Comment by ghost** [comment]
That it doesn't have a banner makes sense, as it's normally only launchable through the System Settings. IIRC it also has no name, displaying as "???" in the title selector. It does, however, have an icon.

**Comment by ghost** [comment]
Can confirm that it doesn't have a banner. I dumped it through other means, and its exefs just contains code and icon.

**Comment by neobrain** [comment]
Excellent, thanks for verifying this!

Future versions of braindump will just ignore non-code sections of zero size, then. Keeping the issue open until that's implemented.

**Comment by ghost** [comment]
I assume this was fixed with the last release, so I'll close it now.
