### ISSUE TITLE
Sky3DS+ support

### ISSUE THREAD

**Issue by ghost** [neobrain/braindump#20]
I tried to use Sky3DS+ to dump some decrypted ROM from encrypted one. It works great. But before entering the app selection, if I choose to switch to another game through Sky3DS buttons, the new _false_ cartridge doesn't appear. You must leave Homebrew Launcher, switch to a game, return to HBL and then use braindump.

Is it an issue of braindump or HBL ? Could someone try to fix it ?

**Comment by TruePikachu** [comment]
It would be of HBL, since that is what discovers the titles.

**Comment by ghost** [comment]
Find a quicker solution: while in HBL, switch to another game, eject and reinsert the linker, open app selection again and the new game will appear.

EDIT: Well, it seems to be quick enough for me. Sorry for the inconvenience. It's still quite interesting to know that braindump is able to dump CXI from encrypted ROM.

**Comment by ghost** [comment]
Thanks for your answer @TruePikachu.

I close this issue since this doesn't concern braindump. Feel free to reopen if needed.

**Comment by Patron182** [comment]
@megadrifter-pt I solved this making a homebrew application, i hope it helps you, you can reload the game pressing A and then just go back to HBL pressing START, the game will be refreshed whitout extracting it.

(link censored)

**Comment by ghost** [comment]
@Patron182 Nice, I'll try this later. Thanks for the contribution.

**Comment by neobrain** [comment]
@Patron182 Please don't put random binary-only programs on this issue tracker. For the time being, I removed the offending link, but feel free to post it again including a source link.

Thanks!
