### ISSUE TITLE
Shouldn't the file extension of the dump be cci?

### ISSUE THREAD

**Issue by mariomadproductions** [neobrain/braindump#22]
Isn't CXI a ROM component, and CCI the ROM?

**Comment by neobrain** [comment]
Depends on your definition of "ROM component", but since braindump doesn't dump the manual and other NCSD partitions (in fact, it doesn't even dump an NCSD but just an NCCH), CXI is indeed the correct extension as far as I can tell.

**Comment by mariomadproductions** [comment]
I think I understand, but does that mean that the CXI braindump makes is a "good" dump - i.e. byte-for-byte identical as a CXI extracted from a ROM dumped with gateway/uncart?

**Comment by ihaveamac** [comment]
no, braindump can't dump everything since it's a userland application.

**Comment by neobrain** [comment]
> no, braindump can't dump everything since it's a userland application.

^ this. Use tools other than braindump if you need a less lossy dump. Actually in general, never throw your cartridge away because "you already dumped it".

**Comment by mariomadproductions** [comment]
So it is closer to a CXI than a CCI, but it isn't quite a CXI. Okay.
