### ISSUE TITLE
Undeletable CXI Failed File

### ISSUE THREAD

**Issue by ImJustJoshin** [neobrain/braindump#23]
I was dumping my digital Pokemon Omega Ruby game after it failed twice before (I uninstalled and reinstalled) and everything was going smoothly until just before it was near completion I get an error saying that I didn't have enough space but that couldn't true I still have 6.7 GB left and the dump was already near done. So I put my SD card into my computer and try deleting the CXI file to realize that I can't... along with every other file on my SD card. This has never happened before. FBI says the partition is incorrect but it was able to delete anything and everything before the error occured just fine.

Console: O3DS CFW Luma 3ds with Arm9loadhax 11.0U

EDIT: I have been going through Decrypt9 and EmuNand9 to see if I can just use my backups to restore my system and they both are switching between Emunand and Rednand as if it can't tell which one I am using when it usually showed GW Emunand (I know Emunand and Rednand are similar).

EDIT 2: Decrypt9 can no longer get my system info as it 'Cannot read my sysNand'

EDIT 3: After the error I got on my 3DS I put my SD Card into my computer to find out that it has become write protected (which is wasn't before and it wasn't to my doing) and I have researched ways to get rid of this write protection and all has failed. My SD card is **useless** now.

**Comment by ihaveamac** [comment]
this is probably a filesystem issue. backup the SD card contents and format it. to back up emu/rednand you might need to use external tools, if you can't write to the SD card.

**Comment by ImJustJoshin** [comment]
I believe I can still write to the SD card but once I do whatever I add cannot be deleted

Nope can't write or delete anything on the SD but it's a good thing I backed up before

**Comment by ImJustJoshin** [comment]
I merged my sysNand and Emunand when I got Arm9 so it would load straight into Luma so would I still do an Emunand backup or a sysnand backup?

**Comment by ImJustJoshin** [comment]
I cant format it either my SD Card has become write protected but not by my own doing. The lock on my SD Card is set to unlocked and there was nothing else I was doing to even come close to the SD Card lock settings so I couldn't have been me

**Comment by ImJustJoshin** [comment]
Alright just got a new SD Card and I am trying again to see if it was bad luck I got the first time around or if it's the actual program

**Comment by ImJustJoshin** [comment]
Alright it went through! It finished and Im guessing I got the short end of the stick with the last dump so I guess it was just my SD Card. Case Closed
