### ISSUE TITLE
Alpha Sapphire dump not working

### ISSUE THREAD

**Issue by kiranrules123** [neobrain/braindump#27]
Hi, I am trying to dump Pokemon: Alpha Sapphire, but it is not working. This Alpha Sapphire is from the eShop. I have sucessfully dumped a pokemon y cartridge, but this doesn't work. I open up braindump, select my game and then it does the blinking to get to braindump, but it always stops with black on top and yellow on bottom.

**Comment by TruePikachu** [comment]
I had no issue dumping my AS cart, what System Version?

**Comment by kiranrules123** [comment]
11.1.0.34U, and mine isnt a cartridge, its eshop

**Comment by ihaveamac** [comment]
11.1 added PASLR against OR/AS. nothing you can do until smealum fixes *hax to work with titles that have PASLR.

**Comment by neobrain** [comment]
What they said. It's a limitation of the mechanism provided by the homebrew environment employed by braindump, not a bug in the application itself.

Use GodMode9 instead if you can.
