### ISSUE TITLE
Pokémon Sun and Moon Demo dump not working

### ISSUE THREAD

**Issue by ghost** [neobrain/braindump#28]
Like it says above, Pokémon Sun and Moon Demo dump not working.
Running Old 3ds 11.1U and Grid Launcher via Basehaxx

**Comment by TruePikachu** [comment]
Likely related to the PASLR of #27, but needs confirmation.

**Comment by TruePikachu** [comment]
Are dumps of other games working correctly?

**Comment by ghost** [comment]
Nope. After selecting app and opening, crashes on yellow screen.

**Comment by khang06** [comment]
That's because it uses 9.6 crypto.
