### ISSUE TITLE
Cube creator 3d won't dump, 

### ISSUE THREAD

**Issue by M-1-RLG** [neobrain/braindump#29]
I wish it would because I hate the music in this game

**Comment by TruePikachu** [comment]
Can you elaborate on what happens when you try dumping it?

**Comment by M-1-RLG** [comment]
Just red screen and freezes

**Comment by Dark124** [comment]
Just red screen and freezes

**Comment by neobrain** [comment]
Red screen means the game is not supported by HANS, and as such not by braindump either as it's using the same underlying mechanism as HANS.

If you have ARM9 code execution, use GodMode9 instead.
