### ISSUE TITLE
Downloaded videos fail to dump

### ISSUE THREAD

**Issue by einstein95** [neobrain/braindump#3]
Videos, like the Majora's Mask 3D trailer, crash braindump to a yellow screen.

**Comment by neobrain** [comment]
Can you launch those trailers regularly at all?

**Comment by einstein95** [comment]
Yeah, they launch fine whether via home menu or via HANS.

**Comment by neobrain** [comment]
Strangely, dumping the MM3D trailer worked just fine for me (title ID 0x0004000000165b00) .. Do you happen to know the title ID of your trailer? Is there a chance I downloaded a different trailer from the eShop?

**Comment by einstein95** [comment]
Okay, I was incorrect in saying that MM3D trailer doesn't work. It appears that only some videos (of which I have only 2) are undumpable and fail to run via HANS.These videos are the Legend of Zelda: 3D Trailer and DKC Returns 3D Trailer. These were also removed from the eShop.

**Comment by neobrain** [comment]
I can't tell which videos you are referring to, since there are multiple titles on the eshop with those names. Please provide instructions on where I can get these titles on the eshop, specifically.

**Comment by einstein95** [comment]
> These were also removed from the eShop.

They were from the 2013 Nintendo Direct trailer.

**Comment by mariomadproductions** [comment]
I got them to work. Maybe I have different versions of the trailers than you do, or maybe you just have to restart. I have a Europe or UK 3DS.

**Comment by einstein95** [comment]
They dump fine using latest version.

**Comment by neobrain** [comment]
That's interesting, thanks for testing again :)
