### ISSUE TITLE
Problem Dumping: always dumps app 0004001000022100

### ISSUE THREAD

**Issue by LemonatedCat** [neobrain/braindump#37]
Like you can read in the title, braindump always just dumps application 0004001000022100 (I do not know what application that is tho) and i can't select titles.

**Comment by TruePikachu** [comment]
The title is EUR Download Play. This would be an issue with the *hax, not BrainDump.

**Comment by LemonatedCat** [comment]
Oops, forgot i had to use some *hax to open it.... I have CFW, so i'd need
a binary....

Am 29.03.2017 04:14 schrieb "Chris Dusto" <notifications@github.com>:

**Comment by TruePikachu** [comment]
Unfortunately, BrainDump _depends_ on *hax chainloading to determine what app to dump; a .cia (or similar) just isn't possible to create.

**Comment by neobrain** [comment]
No love for trolls.
