### ISSUE TITLE
Red screen

### ISSUE THREAD

**Issue by ToadillerYT** [neobrain/braindump#40]
Upon load, I see the numbers and whatnot indicating that homebrew launcher is loading it, but then after that I just get a red screen. Running brain dump w/o dir. o3ds 11.4.0-37U sysnand, w/ boot9strap, Lumacfw, previously had arm9loaderhax installed but updated to boot9strap.

**Comment by neobrain** [comment]
It means the application you are trying to dump is not supported by HANS, and as such not by braindump either.

Note if you have ARM9 code execution, you can (and should) just use GodMode9.

**Comment by ToadillerYT** [comment]
Thanks Mr. Wasserka.
