### ISSUE TITLE
Homebrew Rosalina

### ISSUE THREAD

**Issue by sermakk** [neobrain/braindump#41]
Hello i want to dump omega ruby but when i try and use braindump it says rosalina doesn't support something about titles and basically doesn't work...

Also when trying to use Decrypt9WIP it just crashes back to the home menu...Any help?

**Comment by Cladshack** [comment]
The same thing is happening to me when i try to dump pokemon moon

**Comment by ShadowNA** [comment]
You habe to use godmode9

**Comment by Cladshack** [comment]
how do i do that

**Comment by neobrain** [comment]
Use GodMode9 indeed - you shouldn't be using braindump if you have ARM9 code execution.

**Comment by ShadowNA** [comment]
You asked how to do it:
https://3ds.guide/godmode9-usage.html
