### ISSUE TITLE
ラビリンスの彼方 Yellow Screen

### ISSUE THREAD

**Issue by tnsicdr** [neobrain/braindump#8]
When opening the cartridge version of ラビリンスの彼方 on my N3DS 10.1.0-27J, I'm greeted with a yellow screen on the bottom display, and nothing on the top. 

The game was released in 2012, so it's going to be Pre-9.6 encryption.

**Comment by TruePikachu** [comment]
This might be related to https://github.com/smealum/ninjhax2.x/issues/3

EDIT: The same occurs when you launch it through HANS, right?

**Comment by tnsicdr** [comment]
Hadn't tried that before, but can confirm that it's the same there. Looks like this can be closed then.
